### ISSUE TITLE
Problem with dual-arms robot

### ISSUE THREAD

**Issue by cangjiaxaun** [JenniferBuehler/jaco-arm-pkgs#6] opened 2016-07-27 16:09 UTC
Hello there,
I am currently trying to conduct simulation with a robot with two arm in gazebo based on this repository. 

Here is the problem I met, I'm trying to control the left and right arm with the **gzplugin_joint_control**. What I do is simply reuse the **gzplugin_joint_control** macro twice, first the left arm and then the right arm, with different namespaces. But when running the program I got "_Joint name right_arm_0_joint not found in joint controller joints._" for **gazebo_joint_state_client** plugin and **gazebo_joint_trajectory_server** plugin. 

I printed the names of the joint in `jntMap` and find it only have the joints from the left arm. I tried to only use the **gzplugin_joint_control** macro with the right arm and find everything works well. I guess there may be some thing that was initiate when first use the maco and not changed when second use. 

My implementation is at here: https://github.com/cangjiaxaun/segway.git
The **segway_gazebo_controlled.launch** file in the launch folder is the file that have the problem I described above.

**Comment by JenniferBuehler** [comment] 2016-07-27 16:12
Hi,
thanks for reporting this. I haven't tested on two arms, so I will need to look at it, which I will do as soon as I get the time (hopefully in the next 1-3 days) and will then reply here.
Regards
Jennifer

**Comment by JenniferBuehler** [comment] 2016-07-30 09:36
Hi, I'm looking at this today.  I checked out the code where your error is printed (it's in [joint-control-pkgs](https://github.com/JenniferBuehler/joint-control-pkgs), gazebo_joint_control/GazeboJointStateClient.cpp). You say jntMap shows only names for one arm. This means they haven't been loaded into Gazebo correctly... would you mind sending me your output? Because I still need arm_stand_left.urdf.xacro (and maybe other files you added?) which I can't find in your repository.

Cheers
Jenny

**Comment by JenniferBuehler** [comment] 2016-07-30 09:39
Never mind I just make fake arm_stand xacros myself and now I reproduced your error. Nice two-armed Segway! :) I'll report as soon as I fixed the issue.

**Comment by cangjiaxaun** [comment] 2016-07-30 10:54
Thank you:) Glad you reproduce that error, looking firward to see this bug fixed earlier😄

**Comment by JenniferBuehler** [comment] 2016-07-30 11:20
Hi, this was actually an issue in joint-control-pkgs. Thanks for reporting this and providing me with this nice two-arm model so I could test it easily. it should now work, you only have to do a `git pull` of the joint-control-pkgs repository. Let me know if it works.

I did `roslaunch segway segway_gazebo_controlled.launch load_joint_state_publisher:=true` and I can move both arms joints.

**Comment by cangjiaxaun** [comment] 2016-07-30 12:38
Wow you are so efficient!

But I'm afraid I can't trst it now. I'm go to a conference right now and I can't get access to my computer until 5th Aug.

Thank you very much for fix this error so quickly!

**Comment by cangjiaxaun** [comment] 2016-08-09 09:08
Hi, Jennifer, I have just successfully set two end points, and move the left and right arm to these points in gazebo. Thank you for your repository and prompt reply! Next I'm going to grasp something :)

**Comment by JenniferBuehler** [comment] 2016-08-09 23:48
I'm glad it worked!! We'll see how it plays along with MoveIt... you should maybe try the [MoveIt Tutorial](https://github.com/JenniferBuehler/jaco-arm-pkgs/wiki/Testing-Jaco-with-MoveIt) first. You will have to create a MoveIt configuration for the whole robot with both arms, with different names for the planning groups of each arm. That's a bit more work than with only one arm, let me know if you have any questions on that.

Looking forward to see how it works :)
Jenny

**Comment by JenniferBuehler** [comment] 2017-05-21 03:35
Presuming this issue was fixed, but as there is no more feedback, closing this issue. Please re-open if the same issue pops up again.

**Closed as completed by JenniferBuehler** 2017-05-21 03:35 UTC
