### ISSUE TITLE
Some issues of running Gazebo & Move it! & (c++/python API)

### ISSUE THREAD

**Issue by ditoec** [JenniferBuehler/jaco-arm-pkgs#1] opened 2016-03-24 20:57 UTC
Hi Jennifer,

This might be a little bit out of context, but after I finished the Gazebo+Moveit+Rviz tutorial, I tried to use C++/Python API to control the arm, and came across following issues :+1: 
1. getCurrentPose( ee ) doesnt return a correct pose whatever link that I enter as a parameter ( I checked it using tf subscriber ). I also tried another robot model (UR10) and figured out that getCurrentPose() function itself seems fine.
2. I cannot set 6_hand_limb as end effector, but I can set fingers_base_link as an end effector
3. If I set the group to "All", the motion planner seems to be unable to solve any kind of pose. Setting the group to "Arm" will solve this problem. But the downside is, sometimes the trajectory still make the fingers collide with object. My assumption is, if we plan for "Arm" group only, then Moveit! will ignore the rest of the robot for collision checking, please correct me if I'm wrong.

Thanks very much and great job !

**Comment by JenniferBuehler** [comment] 2016-03-25 01:49
Hi Dito,

thanks for reporting this. A few questions about the points:
1. Which specific getCurrentPose() function did you test?
2.  In which context did you try to set the end effector? Are you referring to a particular tutorial? This is strange, I have always only used 6_hand_limb, it would be interesting to know when it doesn't work.
3. Are you using the jaco_on_table example, or do you have another URDF model? If it has other movable joints (e.g. wheels) you have to add them as passive joints in the configuration. I should probably make this more clear in the tutorials... What error is reported when you try to plan with "All"?  
   The fingers actually _do_ collide with the object sometimes, which is a "flaw" of the MoveIt! collision checker: It checks collisions with objects only at the trajectory key frames. If there is a collision in-between frames, it is not recognized. I have not implemented a fix for this yet, though I think this is something of rather high priority which should be done soon. While I was testing with the real arm, I always enabled the path visualization in RViz to check whether it was such a trajectory candidate and then aborted the execution. So not very nice approach ;) It doesn't happen all the time, but that's a thing I am planning to address soon.

**Comment by ditoec** [comment] 2016-03-25 10:10
Hi Jennifer,

This is the simple python script that  I use (answer for point 1 and 2) ::
`

```
   t = tf.TransformListener()
groups = "All"
ee = "6_hand_limb"
moveit_commander.roscpp_initialize(sys.argv)
robot = moveit_commander.RobotCommander()
scene = moveit_commander.PlanningSceneInterface()
group = moveit_commander.MoveGroupCommander(groups)

display_trajectory_publisher = rospy.Publisher('/move_group/display_planned_path',moveit_msgs.msg.DisplayTrajectory)

print "============ Waiting for TF..."
rospy.sleep(1)
print "============ Starting script"
group.set_pose_reference_frame('/world')
print "============ Planning frame: %s" % group.get_planning_frame()
group.set_end_effector_link(ee)
print "============ End Effector frame: %s" % group.get_end_effector_link()

print "============ Printing EE pose from Moveit!"
print group.get_current_pose().pose
print "============ Printing EE pose from TF"
    (translation,rotation) = t.lookupTransform("world", ee, rospy.Time(0))
print translation
print rotation

x = 0.35
y = 0
z = 1.05
group.set_pose_target([x, y, z,0,0,0,1])
group.plan()`
```

And this is what I got from the shell output ::

> File "/home/dito/Dropbox/catkin_ws/src/cog_arch/src/test_arm.py", line 38, in test_arm
>     group.set_end_effector_link(ee)
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 84, in set_end_effector_link
>     raise MoveItCommanderException("Unable to set end efector link")
> moveit_commander.exception.MoveItCommanderException: Unable to set end efector link

Changing the EE with "fingers_base_link","9_fingers_index_tip" didn't solve the problem, so I changed the group to "Arm", and this is the output ::

> ============ Starting script
> ============ Planning frame: /world
> ============ End Effector frame: 6_hand_limb
> ============ Printing EE pose from Moveit!
> position: 
>   x: 1.25387849668
>   y: 0.521161593216
>   z: 0.803172974345
> orientation: 
>   x: -0.696364240271
>   y: 0.696364240271
>   z: 0.122787804245
>   w: 0.122787804248
> ============ Printing EE pose from TF
> (0.9106080000034783, 0.2131601303369124, 1.29536212684601)
> (-0.011884256279842752, -0.0074926399120764904, 0.9673839509059211, 0.2529247246306166)

As you can see the EE pose that group.get_current_pose() returned doesn't match with what TF returned ( TF pose is the right one ).

For the 3rd point, I use your URDF file, but now I can plan the robot's movement using "6_hand_link" as end effector after I realize that "6_hand_link" and "fingers_base_link" has a different frame orientation :) As for the finger collision part, yeah I guess we really need to solve that because it is quite crucial in terms of doing pick and place activity. Thanks for your help !!

**Comment by JenniferBuehler** [comment] 2016-03-25 17:28
Hm, the difference between /tf and the MoveIt commander is a bit strange, though I must admit I haven't used the python API for MoveIt yet. When using both groups in RViz, it works for me. Does the motion planning with MoveIt+RViz (as in [this tutorial](https://github.com/JenniferBuehler/jaco-arm-pkgs/wiki/Testing-Jaco-with-MoveIt)) work with both groups? If yes, then the configuration should be ok...

Which ROS dist are you using btw?

I'm not sure what the MoveIt "commander" does in getCurrentPose() (and I'm a bit lazy to look it up now), but maybe it doesn't return the pose in the /world, but relative to the robot origin, even though the frame is set to /world. As said, I'm only using C++, so I'm afraid I'm not of much help here. If I had the time, I'd look into the python interfaces, but I'm pretty busy at the moment with finalizing all the packages for the current project. Let me know if you end up finding the issue, it would be interesting to know. Maybe it's got nothing to do with the python interfaces at all.

When I get the time, I'll try to reproduce the problem in C++ and see if it's the same problem there. Will report back here then.

**Comment by JenniferBuehler** [comment] 2016-05-12 09:30
Hi Dito,

I presume that you have solved this issue, as you are working on the real robot now? Can I close this?

**Closed as completed** 2016-06-07 12:06 UTC
